### ISSUE TITLE
0x04 AS_REP中ticket段是否存在错别字？

### ISSUE THREAD

**Issue by xxxxxyyyy** [daikerSec/windows_protocol#2]
在0x04 AS_REP    4. ticket段中，“在AS_REQ请求里面，是使用krbtgt的hash进行加密的“
这句话里的 “AS_REQ“ 是否应该为 “TGS_REQ”，因为 “AS_REQ” 是使用用户的HASH 加密的时间戳。

**Comment by daikerSec** [comment]
你好，不是的。AS_REQ阶段的预认证是用用户hash加密时间戳，放在PA_DATA里面的ENC_TIMESTAMP里面。这个是请求阶段。然后kdc返回的AS_REP里面的ticket是krbtgt的hash加密的。TGS_REP里面的ticket是服务的hash加密的。其实你也可以这样想，ticket都是使用服务的hash加密的，在AS_REQ阶段的服务是krbtgt，所以是使用krbtgt的hash进行加密，在TGS_REQ请求的服务是具体的服务(比如cifs/主机a)，这个时候就是用主机a的机器用户的hash进行加密的。这里面有个好玩的点就是，TGS_REQ请求的服务是具体的服务，包括krbtgt，那如果请求的服务是krbtgt，那么返回的tgs票据是可以当作tgt票据使用的。

**Comment by daikerSec** [comment]
> 在0x04 AS_REP 4. ticket段中，“在AS_REQ请求里面，是使用krbtgt的hash进行加密的“
> 这句话里的 “AS_REQ“ 是否应该为 “TGS_REQ”，因为 “AS_REQ” 是使用用户的HASH 加密的时间戳。

你好，不是的。AS_REQ阶段的预认证是用用户hash加密时间戳，放在PA_DATA里面的ENC_TIMESTAMP里面。这个是请求阶段。然后kdc返回的AS_REP里面的ticket是krbtgt的hash加密的。TGS_REP里面的ticket是服务的hash加密的。其实你也可以这样想，ticket都是使用服务的hash加密的，在AS_REQ阶段的服务是krbtgt，所以是使用krbtgt的hash进行加密，在TGS_REQ请求的服务是具体的服务(比如cifs/主机a)，这个时候就是用主机a的机器用户的hash进行加密的。这里面有个好玩的点就是，TGS_REQ请求的服务是具体的服务，包括krbtgt，那如果请求的服务是krbtgt，那么返回的tgs票据是可以当作tgt票据使用的。
