### ISSUE TITLE
kerberos 测试工具2.0报毒

### ISSUE THREAD

**Issue by Thewind-rises** [daikerSec/windows_protocol#7]
如题所述。
而且聚合查杀和云沙箱都没办法检测。

**Comment by daikerSec** [comment]
里面Kerberos 库的内容用到一些Rubeus的代码,应该是被关联到了.很正常,不是漏洞利用工具,也不需要免杀. C#写的,可以拖进ILSpy看下源码,没留后门

**Comment by Thewind-rises** [comment]
好的，非常感谢您的软件，极大地方便了对Kerberos的学习。
